_format_version: "3.0"
_transform: true

# Global CORS plugin
plugins:
  - name: cors
    config:
      origins:
        - "http://localhost:8082"
        - "http://novashop-frontend.eastus.cloudapp.azure.com"
        - "https://novashop-frontend.eastus.cloudapp.azure.com"  # Added HTTPS version
      methods:
        - "GET"
        - "POST"
        - "PUT"
        - "PATCH"
        - "DELETE"
        - "OPTIONS"
      headers:
        - "Accept"
        - "Accept-Version"
        - "Content-Length"
        - "Content-MD5"
        - "Content-Type"
        - "Date"
        - "X-Auth-Token"
        - "Authorization"
        - "X-Requested-With"
        - "Origin"
        # Removed "Access-Control-Allow-Origin" - this is a response header, not request header
      exposed_headers:
        - "X-Auth-Token"
        - "Access-Control-Allow-Origin"
        - "Access-Control-Allow-Credentials"
      credentials: true
      max_age: 86400
      preflight_continue: false  # Kong handles preflight, don't forward to upstream

services:
  - name: auth-service
    url: http://auth-service:5000
    routes:
      - name: auth-routes
        paths:
          - /auth
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        strip_path: false
        preserve_host: false

  - name: users-service
    url: http://auth-service:5000
    routes:
      - name: users-routes
        paths:
          - /users
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        strip_path: false
        preserve_host: false

  - name: product-service
    url: http://product-service:5000
    routes:
      - name: product-routes
        paths:
          - /products
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        strip_path: false
        preserve_host: false
  
  - name: order-service
    url: http://order-service:5000
    routes:
      - name: order-routes
        paths:
          - /order
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        strip_path: false
        preserve_host: false

  - name: payment-service
    url: http://payment-service:5000
    routes:
      - name: payment-routes
        paths:
          - /payment
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        strip_path: false
        preserve_host: false